development:
  adapter: postgresql
  host: localhost
  database: colchonet
  username: colchonet
  password: colchonet

test:
  adapter: postgresql
  host: localhost
  database: colchonet
  username: colchonet
  password: colchonet

production:
  adapter: postgresql
  host: localhost
  database: colchonet
  username: colchonet
  password: colchonet
